### ISSUE TITLE
Consider using Invoke-Build instead of psake

### ISSUE THREAD

**Issue by daviwil** [PowerShellOrg/Plaster#180]
Was chatting with @lzybkr today and he mentioned that he's been enjoying @nightroman's [Invoke-Build](https://github.com/nightroman/Invoke-Build) recently, one of the major benefits being incremental builds.  It can check input files vs output files and only run the tasks needed since the last build.

I know we're sort of invested in psake at the moment, but it might be interesting to see what a comparable Invoke-Build script would look like to see if we end up with a better result.  Roman put together a [thorough comparison](https://github.com/nightroman/Invoke-Build/wiki/Comparison-with-psake) of the features of both Invoke-Build and psake, could be useful for evaluation.

**Comment by nightroman** [comment]
Invoke-Build is well supported and I am looking forward to this development. 

Invoke-Build has a feature that can simplify Plaster build scripts. It supports
Before and After tasks. The Plaster build script uses extra tasks Impl, Pre,
and Post. Thus, in each case either four tasks should be maintained instead of
one or users do not have an easy way to inject their own Pre and Post tasks.

With Invoke-Build you do not have to decide which task should support Pre and
Post steps and maintain four tasks. A user may add Pre and Post task for any
existing Plaster task:

````powershell
    # Synopsis: Invoked after Plaster Build.
    task PostBuild -After Build {
        ...
    }
    
    # Synopsis: Invoked before Plaster Install.
    task PreInstall -Before Install {
        ...
    }
````

**Comment by davegreen** [comment]
That looks very cool! The approach looks very interesting and tasks being available as dynamic parameters is a nice feature. It'll be good to see how it works as an alternative to the psake script we currently use.

**Comment by rkeithhill** [comment]
We went through this eval months ago and IMO not much of the criteria I used then has changed.  First, the build system needs for Plaster itself or the PowerShell module template, are very, very modest.  I don't see a need for incremental builds as we mostly just copy files to a Release dir and optionally analyze/sign them.  Second, the "momentum" picture for Invoke-Build vs psake hasn't really changed.  On PSGallery, Invoke-Build is sitting at 286 downloads vs 3,050 for psake.  BTW psake was only recently added to PSGallery.  It has been primarily downloaded from Chocolatey.org where its download count is currently 13,006.  Third, there are MSDN articles, blog posts, podcasts, etc on psake.  The only Bing search results I get on Invoke-Build are the GitHub repo and the various galleries where it has been uploaded (NuGet, PSGallery, VS Marketplace).

But more important than downloads is the community behind each project.  On psake there are [48](https://github.com/psake/psake/graphs/contributors) contributors including some familiar names from the PowerShell community (dlwyatt, stej, nightroman).  On Invoke-Build, so far it is only nightroman.  

@nightroman  Please do not think that I question the quality of Invoke-Build. I haven't had a chance to use it yet but if @lzybkr likes it, then I'm sure it's top notch.  It's just when there are multiple available tools it can be hard to pick one.  I used criteria that I thought was best.  

All that said, if the greater PowerShell community thinks `psake` is not the right choice, I'm open to that.  But time is running out for changing this for the initial Plaster release which is just a few weeks out.

**Comment by lzybkr** [comment]
Number of downloads/contributors/articles is meaningless if the tool doesn't do what you need.

And if the tool you're using meets your needs, then maybe there is no reason to change.

I plan on using `Invoke-Build` for `PSReadline` and `PowerShell` because incremental builds are valuable and I think the design of `Invoke-Build` is a bit cleaner (e.g. parameters to the build are normal PowerShell parameters).

Maybe incremental doesn't matter for `Plaster`, but I will note that `Analyze` takes 43s on my machine, (which seems way too long), that's the sort of task you'd like to avoid when possible without having to think about it.

**Comment by rkeithhill** [comment]
> if the tool you're using meets your needs, then maybe there is no reason to change.

That's one issue I'm struggling with on this because psake does what we need to build Plaster as well as most "typical script-based" modules.  

We "could" modify the NewModule template to ask the user which build tool they want to use: None, Invoke-Build or psake.  I'm not crazy about that option from a support/testing perspective.  And as a community I'd like to steer folks towards the "ad hoc" standard tools.  

Now I get that some folks don't agree that psake is the "ad hoc" standard for a PowerShell-based build DSL & engine.  What I want is for the majority of influencers in the PowerShell community to agree on one or the other.  If it comes down to an even-ish split then that argues for making this an option for the template.  Perhaps this is something we can query MVPs on at the summit in a couple of weeks.

> note that Analyze takes 43s on my machine

That kinda sucks doesn't it?  We may want to reconsider whether PSSA is invoked as part of the default build task unless that performance improves.  Perhaps move it into the Publish task.  However, incremental build wouldn't help given that we invoke script analyzer on a directory of script files.

**Comment by daviwil** [comment]
Just wanted to mention that I think Keith's reasoning is completely sound in choosing psake for the initial work since it's more familiar in the community.  I just wanted to bring Invoke-Build up as an option in case others hadn't seen it before.  I think it'd definitely be good to give Invoke-Build some more exposure in the community so that others have a chance to try it out.  If the community gradually decides to use that as the first-rate build tool for PowerShell, we can switch over to it.

However, I think it'd be interesting if someone made a fork of the default template to use Invoke-Build instead for the sake of science :)  It could be a good alternative project template on the Gallery once we've got gallery-deployable templates working (soon...).

I'll be interested to see the build scripts that @lzybkr comes up with for PSReadLine and the PowerShell repo.  Maybe Invoke-Build is a better solution for modules which have binary module components and need to invoke MSBuild?

**Comment by nightroman** [comment]
@rkeithhill, your choice and arguments then and now are solid and wise. And if the initial release is coming soon then it is better to keep things as they are.

The proposal to consider Invoke-Build as the alternative build tool still makes sense. I am biased, indeed. Yet there are facts and the feedback. The tools are at least comparable and have pros and cons. PowerShell users familiar with both tools sometimes choose Invoke-Build.

@lzybkr, if your plans come true then I am looking forward to your suggestions and thoughts.

**Comment by rkeithhill** [comment]
@nightroman It would be cool to see a NewModule template based on Invoke-Build as one of the first community contributed templates.

**Comment by nightroman** [comment]
> It would be cool to see a NewModule template based on Invoke-Build as one of the first community contributed templates.

If there is at least some interest then I will definitely take a look.

**Comment by RamblingCookieMonster** [comment]
So... the community and various references behind psake are nice, but if you look at the actual commits, I'd say it's pretty much dead.  When was the last time features / functionality were added?

Even if @nightroman is the only contributor at the moment, you can see there is active work on the project, e.g. [improving xplat support](https://github.com/nightroman/Invoke-Build/commit/0f708829d2841a41b436b2acbda1cfb0bbeda8c7).

Given that Plaster could help shape which tool becomes more standard, and that Invoke-Build seems to be more capable and a very solid alternative, it might be worth considering using it, regardless of your personal need for it in this project.

I suspect we haven't hit a point where changing from psake as the 'go-to' would be too difficult.  Yes, plenty of people write about it, but I suspect most folks out there using psake are the sort of folks actually writing about it - CI / CD is a hot topic in the PowerShell world, but in the scheme of things, I don't think it's anywhere near critical mass, particularly when talking one component of that pipeline, and a component that many folks simply leave out.  At the very least, you might consider adding support for it, even if you don't replace psake (personally I might lean towards replacing :))

Off topic, but I'll plan to write a quick bit on invoke-build rather than psake.

Cheers!

**Comment by nightroman** [comment]
Here is some *very quick and dirty* preview of build related script changes
(just .ps1, not .json or anything else, doc comments are mostly not changed).

- [.build.ps1](https://github.com/nightroman/Plaster/blob/master/src/Templates/NewModuleInvokeBuild/.build.ps1)
- [build.settings.ps1](https://github.com/nightroman/Plaster/blob/master/src/Templates/NewModuleInvokeBuild/build.settings.ps1)

Changes

- Required variables are checked after dot-sourcing settings
- Renamed *build.psake.ps1* to *.build.ps1*, the default IB script
- Removed all `Pre`, `Post`, and most of `Impl` tasks
- Kept `BuildImpl`, its dependency is tricky, TODO
- Removed `?`, the command `Invoke-Build ?` is supported literally

This is not a PR in any way, just a preview of syntactically valid scripts adapted for Invoke-Build.

**Comment by daviwil** [comment]
Hey @RamblingCookieMonster, definitely write about Invoke-Build, that would be a great conversation starter!

@nightroman Those changes look pretty straightforward, not bad at all.  I suppose we could even move the `Assert-Variable` calls into the tasks themselves to replace the `-requiredVariables` parameter that psake provides.  Looking at the diff here was helpful:

https://github.com/nightroman/Plaster/commit/5d0cef2a6d0ad0957237b295c03c13a4e0b7e7b0

**Comment by nightroman** [comment]
There is an [article](http://www.the-little-things.net/blog/2016/07/31/powershell-new-project-psmodulebuild/)! @zloeber, thank you once again.

**Comment by nightroman** [comment]
I am going to close my demo-fork. There is a much better and working example, [PSScaffold](https://github.com/RedeployAB/PSScaffold) which scaffolds structures of PowerShell modules and build pipelines with Invoke-Build as the task runner. This is not "Pester with Invoke-Build". But it is conceptually similar and in some ways related to Pester.

**Comment by zloeber** [comment]
How did I miss that project? I've just started going down the path of using Plaster to do this very thing.

**Comment by nightroman** [comment]
@zloeber The initial commit is just 2 days ago. As far as I understand (@KarlGW may correct me), a group of people decided to make *their* typical modules creation easier. It is not that universal as Plaster, by design.

**Comment by KarlGW** [comment]
@nightroman @zloeber Yes that is correct, initial commit was just the other day. It has been used internally for a while as an inhouse tool before me and the rest company decided we would release it publicly to try to contribute to the PowerShell community. And yes, it's more intended for how we ourselves build our modules, quite inspired by Rambling Cookie Monsters articles, and the build configuration for Invoke-Build was based on xainey's very great article: https://xainey.github.io/2017/powershell-module-pipeline/.

**Comment by PowerSchill** [comment]
I just encountered an issue with building Plaster on OSX in that PSAKE is not currently functioning in PS Core on OSX as documented in https://github.com/psake/psake/issues/197.

**Comment by larssb** [comment]
@PowerSchill that makes two of us. I'm going to use Invoke-build in my Plaster template instead.....let's see how that goes down. Will come back with some feedback.

**Comment by PowerSchill** [comment]
In https://github.com/psake/psake/issues/204 @daviwil mentioned that he and @rkeithhill have assumed ownership of psake. Should we expect a version of psake that supports PS Core? Would the maintainers of this project be open to a pull request (not done yet) converting from psake to InvokeBuild?

**Comment by rkeithhill** [comment]
Yes the plan is to make PSake work cross-platform.  At **this point in time**, I'd prefer to stick with PSake for this repo but that may change if the PSake work doesn't move quickly enough.  

Regarding `building` Plaster on non-Windows platforms, for the most part you only need to do this in prep for publishing the module.  The module can be imported/debugged directly from the `src` dir.

**Comment by PowerSchill** [comment]
True, but my templates utilize the same build script for Plaster so I would have to rebuild the build script anyways to get them to work on non-Windows platforms.
